/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import entidades.Fruta;
import java.util.ArrayList;
import javax.swing.JComboBox;

/**
 *
 * @author sergio
 */
public class FCombox extends javax.swing.JFrame {

    /**
     * Creates new form FCombox
     */
    ArrayList<String> arrFrutas = new ArrayList<>();
    
    public FCombox() {
        initComponents();
        
        cargaClaseFrutas(jcClaseFrutas);
        
         /* initFrutas(arrFrutas){
            arrFrutas.add(2)
                } carga las frutas
         */
         //cargaCombox(arrayList arr ,JComboBox jc )
        
        cbFabricantes.addItem("Mazda");
        cbFabricantes.addItem("Volvo");
        
    }

    private void cargaClaseFrutas(JComboBox jc){
        
        Fruta f=new Fruta(1,"Manzana");
        Fruta f2=new Fruta(2,"Pera");
        
        jc.addItem(f);
        jc.addItem(f2);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbFabricantes = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lblSeleccion = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnElimina = new javax.swing.JButton();
        jcClaseFrutas = new javax.swing.JComboBox<>();
        btnClaseFrutas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbFabricantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Renault", "Toyota", "Mercedes", "Audi", "Seat" }));

        jLabel1.setText("Modelo Seleccionado:");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnElimina.setText("Elimina");
        btnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaActionPerformed(evt);
            }
        });

        btnClaseFrutas.setText("Aceptar");
        btnClaseFrutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaseFrutasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcClaseFrutas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbFabricantes, 0, 119, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnElimina)
                                .addComponent(btnAceptar))
                            .addComponent(btnClaseFrutas))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFabricantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar))
                .addGap(18, 18, 18)
                .addComponent(btnElimina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcClaseFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClaseFrutas))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        //System.out.println("Pulsado boton");
        //seleccionar el valor del cbFabricantes
        
        //cbFabricantes.getSelectedIndex()
        //String cadena=cbFabricantes.getItemAt(cbFabricantes.getSelectedIndex());
        String cadena=cbFabricantes.getSelectedItem().toString() ;
        lblSeleccion.setText(cadena);
        //MuestraValoresCombox(arrayList ,JComboBox jc);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed
        // TODO add your handling code here:
        
        cbFabricantes.removeItemAt(cbFabricantes.getSelectedIndex());
        
    }//GEN-LAST:event_btnEliminaActionPerformed

    private void btnClaseFrutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaseFrutasActionPerformed
        // TODO add your handling code here:
        
        Fruta fseleccionada = (Fruta)jcClaseFrutas.getSelectedItem();
        System.out.println("Fruta id:"+fseleccionada.id);
        System.out.println("Fruta nombre:"+fseleccionada.nombre);
        
    }//GEN-LAST:event_btnClaseFrutasActionPerformed

    private void MuestraValoresCombox(JComboBox jc){
    
        for(int index=0;index<jc.getItemCount();index++ ){
            System.out.println(""+jc.getItemAt(index));
        }
        
    }
    
    private boolean ExisteValorCombox(String valor){
    
       
    return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FCombox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FCombox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FCombox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FCombox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FCombox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnClaseFrutas;
    private javax.swing.JButton btnElimina;
    private javax.swing.JComboBox<String> cbFabricantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jcClaseFrutas;
    private javax.swing.JLabel lblSeleccion;
    // End of variables declaration//GEN-END:variables
}
