/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author sergio
 */
public class FListBox extends javax.swing.JFrame {

    private DefaultListModel<String> modeloCandidatos;
    private DefaultListModel<String> modeloSeleccionados;
    /**
     * Creates new form FListBox
     */
    public FListBox() {
        initComponents();
        InicializaListBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstCandidatos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSeleccionados = new javax.swing.JList<>();
        btnPasaSeleccion = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(lstCandidatos);

        jScrollPane2.setViewportView(lstSeleccionados);

        btnPasaSeleccion.setText(">");
        btnPasaSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasaSeleccionActionPerformed(evt);
            }
        });

        jButton2.setText(">>");

        jLabel1.setText("Candidatos");

        jLabel2.setText("Seleccionados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPasaSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(btnPasaSeleccion)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPasaSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasaSeleccionActionPerformed
        // TODO add your handling code here:
        
        
        //Eliminamos un indice accediendo al modelo desde el listBox
        /*DefaultListModel<String> modelo=(DefaultListModel)lstCandidatos.getModel();
        int indice=lstCandidatos.getSelectedIndex();
        modelo.remove(indice);
        */
        
        //Eliminamos varios indices
        // accediendo al modelo desde el listBox
        /*DefaultListModel<String> modelo=(DefaultListModel)lstCandidatos.getModel();
        int[] seleccionados=lstCandidatos.getSelectedIndices();
        int i;
        for(i=0;i<seleccionados.length;i++)
            modelo.remove(i);
        */
                
        //mostramos el valor seleccionado
        //System.out.println(""+lstCandidatos.getSelectedValue());        
        for(String selecc:lstCandidatos.getSelectedValuesList()){
            System.out.println(""+selecc);
            modeloSeleccionados.addElement(selecc);
            modeloCandidatos.removeElement(selecc);
        }
        
        
    }//GEN-LAST:event_btnPasaSeleccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FListBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FListBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FListBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FListBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FListBox().setVisible(true);
            }
        });
    }
    
    private void InicializaListBox(){
        modeloCandidatos=new DefaultListModel<>();
        modeloSeleccionados=new DefaultListModel<>();
        
        lstCandidatos.setModel(modeloCandidatos);
        lstSeleccionados.setModel(modeloSeleccionados);
        
        modeloCandidatos.addElement("Samuel");
        modeloCandidatos.addElement("Adolfo");
        modeloCandidatos.addElement("Javier");
        modeloCandidatos.addElement("Alvaro");
        modeloCandidatos.addElement("Carmen");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPasaSeleccion;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstCandidatos;
    private javax.swing.JList<String> lstSeleccionados;
    // End of variables declaration//GEN-END:variables
}
